### ISSUE TITLE
Introduce Command Pattern to Event Handling in index.js

### ISSUE THREAD

**Issue by estellise-yukihime** [SigfridGK/discord-bot#2]
The current implementation in index.js is handling multiple multiline events which can result to complexity, making it harder and harder to maintain and scale.

These event handlers can be in a seperate module.

example:

/command/event/

client_ready_event.js
```
export default async function ClientReadyEvent (readyClient) { }
```

client_interaction_create_event.js
```
export default async function ClientInteractionReadyEvent(async interaction){}
```

events.js
```
import { ClientReadyEvent } from ./client_ready.event.js
import { ClientInteractionReadyEvent } from ./client_interaction_create_event.js

export { ClientReadyEvent, ClientInteractionReadyEvent };
```

index.js
```
import { ClientReadyEvent } from ./command/events/event.js

client.once(Events.ClientReady, ClientReadyEvent);
```

**Comment by SigfridGK** [comment]
@estellise-yukihime 
Hello can you check newly Update:
https://github.com/SigfridGK/discord-bot/commit/13ca72693c72a54b6f9030533e3cf5f0b8191abb

**Comment by estellise-yukihime** [comment]
This is an improvement, but lets not stop there, let's keep improving more.

I'll close this issue for now, while I'm looking parts for improvement.
